---
output: github_document
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, include=FALSE}
library(tidyverse)
theme_set(theme_light())
```


# Hi, I'm Devin 

<!-- badges: start -->
<!-- badges: end -->

I'm a Data Scientist with experience working in academic, private, and non-profit research. I work mostly in R but am comfortable with Python and enjoy working in SQL. I'm currently pursuing a PhD in Experimental Psychology, conducting experiments and learning how to leverage existing data to understand human as well as organizational behavior.



```{r}
#Simulation for power analysis
n_sims <- 100

p_vals <- c()

for(i in 1:n_sims){
  control_group <- rnorm(60, 1, 1)
  experimental_group <- rnorm(60, 1.5, 1)
  p_vals[i] <- t.test(control_group, experimental_group)$p.value
}

statistical_power <- mean(p_vals < .05)
statistical_power
```




```{r,echo=FALSE}
set.seed(2022)
control_group <- rnorm(60, 1, 1)
experimental_group <- rnorm(60, 1.5, 1)

sim_data <- as.data.frame(control_group)
sim_data$experimental_group <- experimental_group

sim_data |>
  pivot_longer(names_to = "group",
               values_to = "values",
               cols = c(control_group, experimental_group)) |>
  group_by(group) |>
  summarise(mean_response = mean(values),
            sd = sd(values),
            n = n(),
            sem = sd / sqrt(n)) |>
  ggplot(aes(group, mean_response, fill = group)) +
  geom_col(width = .6) +
  geom_errorbar(mapping = aes(ymin = mean_response - sem,
                              ymax = mean_response + sem),
                width = .4) +
  theme(legend.position="none") +
  labs(caption = "t(112.28) = 3.86, p < .001; 
                              Cohen's d = 0.70, 95% CI [0.33, 1.07]")
```


```{r,include=FALSE}

report::report(t.test(experimental_group, control_group))
```
